services:
    app:
        build:
            context: .
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        expose:
            - "9000"
        depends_on:
            mysql:
                condition: service_healthy
        volumes:
            - ./storage:/var/www/storage

    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./public:/var/www/public
            - ./storage:/var/www/storage
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: app
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1" ]
            timeout: 5s
            retries: 10

volumes:
    mysql_data:
